In [1]:
# import library
import numpy as np

#### Array Creation

In [2]:
# create a 1D array
a = np.array([3, 1, 4])
a

array([3, 1, 4])

In [3]:
# create a 2D array
b = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
b

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [4]:
# check the dimensions
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# create an array with all zeros
c = np.zeros(3, dtype = int) # default is floating point unless specified otherwise
c

array([0, 0, 0])

In [6]:
# create an array with all ones
d = np.ones(3, dtype = int)
d

array([1, 1, 1])

In [7]:
# create a full array
e = np.full((2, 3), 9, dtype = int)
e

array([[9, 9, 9],
       [9, 9, 9]])

In [8]:
# create an array with equally spaced numbers
f = np.linspace(1, 10, 15)
f

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

#### Array Indexing

In [9]:
a = np.array([3, 1, 4])
a

array([3, 1, 4])

In [10]:
a[1]

np.int64(1)

In [11]:
a[1] = 9
a

array([3, 9, 4])

In [12]:
# create a 2D array
b = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
b

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [13]:
b[1][1] = b[0][0] + b[1][1] + b[2][2]
b

array([[ 4,  9,  2],
       [ 3, 15,  7],
       [ 8,  1,  6]])

#### Array Slicing

In [14]:
a = np.array([4, 2, 7, 5, 3, 8, 9, 1, 6])
a

array([4, 2, 7, 5, 3, 8, 9, 1, 6])

In [15]:
b = a[2:5]
b

array([7, 5, 3])

In [16]:
# slice from the beginning
a[:3]

array([4, 2, 7])

In [17]:
# slice upto the end
a[-4:]

array([8, 9, 1, 6])

In [18]:
# create a 2D array
b = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
b

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [19]:
c = b[1:, 1:]
print(c)

[[5 7]
 [1 6]]


#### NumPy Data Types
* i - integer
* b - boolean
* u - unsigned integer (whole numbers)
* f - float
* S - string

In [20]:
# check the type for an array
a = np.array([4, 2, 7, 5, 3, 8, 9, 1, 6])
print(a.dtype)

int64


In [21]:
# create an array of strings
b = np.array([2, 8, 5], dtype = 'S')
print(b)
print(b.dtype)

[b'2' b'8' b'5']
|S1


In [22]:
# create an array of floats
c = np.array([1.9, 8.2, 3.7])
print(c)
print(c.dtype)

[1.9 8.2 3.7]
float64


In [23]:
# convert the array of floats to an array of integers
d = c.astype('i')
print(d)
print(d.dtype)

[1 8 3]
int32


#### Array Shape and Reshape

In [24]:
b = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
print(b)
print(b.shape) #prints number of rows and columns
print(b.size) #prints number of elements in 2D array

[[4 9 2]
 [3 5 7]
 [8 1 6]]
(3, 3)
9


In [25]:
# create a 1D array
c = np.array([9, 1, 2, 8, 7, 3, 4, 6, 5])
print(c)

[9 1 2 8 7 3 4 6 5]


In [26]:
# reshape the array (must use all elements in array to reshape)
d = c.reshape(3, 3)
print(d)

[[9 1 2]
 [8 7 3]
 [4 6 5]]


In [27]:
# create a 2D array and flatten it
b = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
f = b.reshape(1, 9)
print(f)

[[4 9 2 3 5 7 8 1 6]]


In [28]:
g = b.ravel()
#both b.flatten() and b.reshape(-1) does same thing
print(g)

[4 9 2 3 5 7 8 1 6]


#### Array Iteration

In [29]:
# create an array and iterate (go through elements one by one in order)
a = np.array([8, 4, 6])
for x in a:
    print(x)

8
4
6


In [30]:
# create a 2D array and iterate
b = np.array([[3, 1], [5, 8]])
for x in b:
    print(x)

[3 1]
[5 8]


In [31]:
for x in b:
    for y in x:
        print(y)

3
1
5
8


In [32]:
# iterate through a multidimensional array using nditer
for x in np.nditer(b):
    print(x)

3
1
5
8


#### Array Join / Split

In [33]:
# join two arrays
a = np.array([6, 8, 3])
b = np.array([7, 2, 5])
c = np.concatenate((a,b))
print(c)

[6 8 3 7 2 5]


In [34]:
# join 2d arrays
c = np.array([[3, 7], [8, 1]])
d = np.array([[9, 2], [4, 6]])
e = np.concatenate((c, d), axis = 0)
print(e)
f = np.concatenate((c, d), axis = 1)
print(f)

[[3 7]
 [8 1]
 [9 2]
 [4 6]]
[[3 7 9 2]
 [8 1 4 6]]


In [35]:
# stack vertically (sames as concatenate /w axis = 0)
g = np.vstack((c, d))
print(g)

[[3 7]
 [8 1]
 [9 2]
 [4 6]]


In [36]:
# stack horizontally (same as concatenate /w axis = 1)
h = np.hstack((c, d))
print(h)

[[3 7 9 2]
 [8 1 4 6]]


In [37]:
# split an array
j = np.array([9, 2, 7, 1, 3, 5])
k = np.array_split(j, 3) # can go over the length of array
print(k)

[array([9, 2]), array([7, 1]), array([3, 5])]


In [38]:
print(k[2])

[3 5]


In [39]:
# split a 2D array
m = np.array([[4, 1], [5, 7], [3, 8], [2, 9]])
print(m)

[[4 1]
 [5 7]
 [3 8]
 [2 9]]


In [40]:
n = np.array_split(m,2)
print(n)

[array([[4, 1],
       [5, 7]]), array([[3, 8],
       [2, 9]])]


In [41]:
print(n[0])

[[4 1]
 [5 7]]


In [42]:
print(n[1])

[[3 8]
 [2 9]]


#### Array Sort / Search

In [43]:
# create a 1D array
a = np.array([2, 7, 1, 8, 3, 9, 5, 4, 6])
print(a)
b = np.sort(a)
print(b)

[2 7 1 8 3 9 5 4 6]
[1 2 3 4 5 6 7 8 9]


In [44]:
# create a 2D array
c = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
print(c)
d = np.sort(c)
print(d)

[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[2 4 9]
 [3 5 7]
 [1 6 8]]


In [45]:
# print the index for a given value
idx = np.where(a == 9)
print(idx)

(array([5]),)


In [46]:
# find the indices of even values
idx = np.where(a%2 == 0)
print(idx)

(array([0, 3, 7, 8]),)


#### Filter an Array

In [47]:
# create an array
a = np.array([2, 7, 1, 8, 3, 9, 5, 4, 6])

# create the filter for the array
filter = (a%2 == 0)

# create a new array with that filter
b = a[filter]
print(b)

[2 8 4 6]


#### Basic Operations

In [48]:
a = np.array([9, 2, 7, 4])
b = np.array([5, 8, 3, 6])

c = a + b
print(c)

[14 10 10 10]


In [49]:
d = 3 * a - 2 * b
print(d)

[ 17 -10  15   0]


In [50]:
e = np.sin(a)
print(e)

[ 0.41211849  0.90929743  0.6569866  -0.7568025 ]


In [51]:
f = np.sqrt(a)
print(f)

[3.         1.41421356 2.64575131 2.        ]


In [52]:
g = np.exp(b)
print(g)

[ 148.4131591  2980.95798704   20.08553692  403.42879349]


In [53]:
h = a.dot(b) # takes both elements of an index from both arrays, multiplies them together, and adds everything
print(h)

106


In [54]:
i = np.array([[1, 3, 4], [5, 7, 2], [5, 7, 2]])
j = np.array([[5, 8, 9], [1, 2, 3], [1, 2, 3]])

k = i.dot(j)
print(k)

[[12 22 30]
 [34 58 72]
 [34 58 72]]
